server:
  port: 8463
logging:
  file: /java/C2S_LOGS/phr/phr.log
info:
  component: Patient Health Record Service
ribbon:
  ReadTimeout: 50000
hystrix.command.default.execution.timeout.enabled: false
spring:
  http:
    multipart:
      max-file-size: 10MB
  datasource:
    # configure url, username and password per environment
    url: jdbc:mysql://localhost:3306/phr?autoReconnect=true
    username: root
    password: admin
c2s:
  phr:
    patientDocumentUploads:
      # List of permitted file extensions for clinical document files uploaded to PHR
      extensionsPermittedToUpload:
        - xml
        - txt
    # Configure document-validator context path based on running instance
    document-validator:
      context-path: "/document-validator"
---
spring.profiles: standalone-ssl
spring:
  profiles:
    include: ssl-default
server:
  context-path: /phr
---
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://${C2S_DB_HOST:phr-db.c2s.com}:${C2S_DB_PORT:3306}/phr?autoReconnect=true
